### ISSUE TITLE
Can't reproduce without image assets.

### ISSUE THREAD

**Issue by kkothari93** [nipunramk/Reducible#4]
I am trying to learn more about the manim library. I am a complete beginner and in the process of searching for some tutorials, I found your content on YouTube. Congratulations on doing such a fantastic job. I thought I will try to learn more from your codebase but in order to reproduce the code, there are a bunch of image assets (for eg, dog.png, rose.jpg etc in JPEGCompression vid) that are needed. Where can I find those?

**Comment by nipunramk** [comment]
@kkothari93 Apologies for the delayed response. You can find the image assets here: https://github.com/nipunramk/Video-Dev/tree/main/assets -- you can download and add any assets to your environment as you need from here.
